---
output:
  pdf_document: default
  html_document: default
---
# Interaction networks, food webs, and complexity in ecology - one-page summary

During this day on interaction networks, we will first (1) introduce the concepts and definitions associated with networks of interactions, and then tackle two general questions regarding interaction networks: (2) how to simplify complexity by considering random matrices to model interactions and (3) how to assess the link between complexity and dynamical stability in empirical data. As a conclusion to the thematic day, we will (4) delve into multiplex networks, i.e. networks combining interactions of different types.

The introductory course covers a variety of topics including networks and their definition, their representation as matrix and their interpretation in dynamical model. Notable theoretical results based on network properties are then reviewed, including results on stability and feasibility, the search for invariant properties structuring the topology of empirical networks, and the general framework of robustness studies, i.e. studies aimed at understanding how species removal affect the rest of the network through cascading extinctions. The introductory course is concluded by a primer on network statistics commonly used to characterize interaction networks, including degree distributions, the randomizations used to generate null predictions, and the models used to assess groups of species interacting in the same way or interacting in a nested fashion.

The simplification of complexity through large ecosystems and random matrices is then presented in a series of steps. The emerging simplicity of systems comprising many species is  explained, with a particular focus on some fingerprint properties that could characterize the predictions of competing models. The use of random interaction matrix can be considered as a shortcut to obtaining such properties, as well as a path to analytical tractability of complex disordered systems.

The link between complexity and stability of empirical food webs is the focus of the third part of the day. By using simple relationships between interaction coefficients and biomasses, and then computing Jacobian matrices, which characterize system stability, the complexity-stability relationship of empirical food webs can be compared with that of their randomized counterparts, which in turn allows for a close examination of ecological hypotheses explaining food web stability.

The last presentation of the day introduces multiplex networks of interactions, i.e. networks in which several types of interactions are represented together. Following on the idea of keystone predators, as introduced by the work of R. Paine on intertidal communities, the modulation of trophic interactions and species parameters by non-trophic interactions is explored through dynamical models confronted with existing data on intertidal systems with both competition and resource consumption. The parallel topologies of trophic and non-trophic interaction networks are then gauged through block models  and random network models in order to assess the effect of network structure on food web feasibility, stability and total biomass. 
