# What types of theoretical models in ecology? (Isa)

## What system? What question? What hypotheses (no maths shown here)

* Question is related to a **specific level of organization** / scale and determine what can be ignored
* Examples of questions and processes of interest for each scale based on our recurrent example plant-herbivore (P-H)
* *Updated Levin's triangle (Bullock 2014) illustrated by different (P-H) models (conceptual, system-specific, generic) with related questions => define variables*

**Categorisation of models**

We identify trade-offs in ecological models, choices between them should be based on our goals.

* Our goal with mechanistic models can be:
  - understanding processes
  - extrapolating beyond observed variables
  - what if ? questioning

The strength of process-based model in general: we capture ecological mechanisms to explain a specific pattern/relationship, but then the model predicts other patterns, beyond the ones that inspired initally the model. The diversity of patterns that are expected from mechanistic models allow to discriminate which model produces patterns the closest from reality. Process-based models feed our understanding of the consequences of the ecological process we modeled.

Possibility of nesting several process-based models in a broader framework (e.g., niche model to get the topology and then use this topology in a dynamical food web model.


* Trade-offs:
  - simple versus complex (number of variables and parameters, number of mechanisms...) (--> complex models are not useful if not enough data. Principle of parsimony)

  - generic versus specific 
  - abstract versus realistic
  - tractable versus intractable (analytical solutions or not ? Calculation time ?)
  - (strategic (=generic+simple) versus tactical (complex+specific)) terminology attributed to Holling)

 * Other axis : data-driven versus process-based models
   - data-driven models are based on data, based on patterns not processes. Limited by the data available. 
    - mechanistic models: based on ecological processes

* **What can be ignored?** The differences in time scale between processes allow to do some approximations: Upper level is slower than lower ones and its dynamics may be ignored depending on the question. Similarly, lower levels can be considered at equilibrium if much faster than the focal dynamics, or averaged (macroscale averaged view of microscale processes => physics statistics).
* **Link between assumptions, model and predictions**, with the risk of overinterpretation: always keep in mind that what mathematical methods is truth only in the context of initial assumptions.
* **The different types of assumptions** (Servedio 2014):
  - Critical assumptions: the ones necessary to answer the question (structure of the model).
  - Exploratory assumptions: the ones to go deeper in the exploration, assess the robustness of the results.
  - Logistical assumptions: the ones that have to deal with tractability.
* **Illustration of assumption types** with the Grazing-optimisation example (De mazancourt et al. 1998):
  - Critical assumptions: two paths of recycling with different rates for plants and herbivores.
  - Exploratory assumptions: change in the functional response.
  - Logistical assumptions: use of deterministic ODEs and continuous time with no space (we'll see all that in more depth in next section).

## What model formalism? (no maths shown here)

* **Types of variables**: quantitative discrete or continuous variables ? How to describe the variables? Example: if stochastic processes: demographic stochasticity has to be with counts (integer). Small populations.
But if large populations where stochasticity is not important: then it is fine to use continuous variables. It could be equivalent to use a lognormal distribution rather than a Poisson distribution.

### Deterministic – stochastic processes

* What is stochasticity ? Give a clear definition here. Use randomness instead ? What is a stochastic model ?
Probabilities around a process

Random environmental conditions : a each time step, probability of have a given value

* **What does stochasticity come from?** 
  - Environmental (eg: perturbations): does not scale with population size and can vary in space and time.
  - Demographic (eg: more or less offsprings, trait variability that will impact biological rates): scales with population size. 
* **When should we account for it** (illustration with pop logistic growth (no math) with addition or not of gaussian noise)
  - for questions related to output variability
  - when output distribution is skewed and mean no more a good predictor (small populations) => when stochastic processes are dominant (ecological or genetical drifts, Allee effect, large demographic stochasticity)
* **When can we use deterministic**: when processes can be summarised with averaged parameters (large populations)
* NB: mention of master equations (deterministic equation summarizing stochastic model) 

* Suggestion: decision tree: 
  - do the processes vary across time and/or space? Yes/No?
  - do the variable studied can vary a lot relative to its average (small or large populations) ? Yes/No ?
  - if Yes -> stochastic model needed.

### Time: discrete – continuous 

How do the processes are structured along time?  when using discrete vs continuous time 

* **What are the underlying assumptions?**
  - *Discrete-time*: 
    - Fixed generation times
    - Synchronization of processes (e.g., seasonal forcing)
    - Sequential processes with specific order (e.g., complex life-cycle) => more transparent 
  - *Continuous time*: 
    - Events can happen at any time
    - Generation overlap
* **Illustration with logistic pop growth** in continuous and discrete time:
  - discrete-time with small ∆t boils down to continuous
  - discrete time have richer dynamics due to a lag
* **Appropriate systems / questions**
  - discrete-time:
    - questions related to phenology
    - seasonal dynamics and synchronized generations
    - complex life cycled
  - continuous-time:
    - generation overlap
    - when processes can happen at any time
* Both can be either stochastic or deterministic

### Accounting for space 
* **None vs spatial**: 
  - In none spatial models, space is assumed homogenous and the scale can be integrated within the units (example: pop density in ind/km2)
  - When does the question need explicit description of space? 
    - When spatial processes impact local dynamics of interest
    - if we are interested in patterns emerging at higher spatial scale from local processes
* **Topology versus Distances explicit**: does geographical positions  matter or only topology?
  - Topology (metapop model): space is represented in the structure of space and strength of connectivity. Adapted to study fragmented landscapes or problems related to structure of connectivity
  - Explicit: distances are explicit; in 1 (Fisher KPP) or two dimensions (grid): adapted to represents fronts, gradients, edge effects or emerging spatial patterns.
* **Discrete within the distance explicit case**: grids vs Continuous (PDE):
  - *Continuous* adapted to model processes occurring progressing locally (diffusion) but not processes with large distance / heterogeneous effects
  - *Grids* with small mesh size can boil down to continuous (sometimes, discretisation is used for a technical approximation of continuous space)  => question of technical relevance.
  - As continuous can be more difficult (math) this can prevent its use (mention of lab inheritance)

  

## What technical choices?

### Analytical – Numerical

What do we gain in making models simple? => Principle of parcimony

* **Analytical solution**: we know the state of the model at any time point given $\frac{dN}{dt} \rightarrow f(t)$
* **Tractable model**: We are able to express equilibrium with parameters and study local stability $\frac{dN}{dt} \rightarrow N^*=f(parameters)$ => we can say generalities about the long term dynamics
* **Intractable models**: 
  - we are obliged to do simulations using numerical algorithm or integration to approximate the dynamics step by step.
  - the results depend on the parameter values and initial conditions.
  - The dimension of the parameter space to explore is exponentially linked to the number of parameters
  - Simulations allow to investigate transient dynamics

### Rules versus Maths

* **What is an agent-based model?** Algorithm which represent processes with a series of rules applied to each agent at each time step using proba: example with birth, death, interactions
* **What is the alternative**: Math => equations: example of ODE, SDE, DE, PDE: what does it mean?
  - ODE: change over time of our variable of interest (SDE; with some stochasticity) => give
  - DE: State at the next time step
  - PDE: Change over time and space
  - Overall idea: Balance between inputs and outputs. See with exponential model?

* **Advantages / Disadvantages**:
Computational versus mahematical skills
  - *ABM*: 
    + The dynamics emerge from elemental processes
    + Simpler to build from empirical knowledge
    + But high computation consumption
    + Rarely tractable
  - *Equations*
    + Use of math and approximation for simplifications
    + Have large analysis power for extreme cases
    + Fast computation
    + Easier to fit to data 
    + The relations between variables are imposed: processes synthetized
* **To what questions / system/ conditions is it most adapted?**
  - *ABM*: 
    + When stochastic processes are dominant (ex: conservation of small pops) 
    + When there are not too many parameters
    + For some questions where processes are difficult to synthesise (behaviour)
    + When there is no math skills around!
  - *Equations*:
    + Whenever processes can be synthesised with average parameters
    + => Large populations
* Such choices are often an inheritance from lab practices and habits.

## Some classical models used in ecology and seen next days 

* Systems of differential equations, no space : 
  - Verhulst (logistic growth), Lotka-Volterra predator-prey (Day 2)
  - Lotka-Volterra, food web niche model (Day 4)
* Spatial systems of differential equations: TIB, Levins’ occupancy (Day3)
* Spatial IBM: Neutral model of biodiversity from Hubbel (Day 3)

A Rmarkdown file is available to provide the code of the illustrations of  section 2.2


#  How to build a model? (Isa)
(1h)  Lecture with interactivity  (and Rmarkdown file for some parts)

* I will present different pictures of different plant-herbivore systems with associated research questions and ask how they will sketch the system (on board) to do a mode.
* I will ask then which formalism they would choose and why (in terms of determinism, time, space) [and we can try writing rules or equations?]
* Then we will focus on a question for which the Rosenzweig-MacArthur model (ODE)  is appropriate, I will write the model on board and ask all the assumptions they could see that are behind the model formulation. We will discuss in which regards they are appropriate for our question. 
* Then we will study line by line a code in R to explain how this could be implemented in R, while also explaining the principle of numerical integration.
* I will let them 5-10min  to run the model and plot some dynamics and ask them how they would use it to answer the question (to introduce the next section).


# How to analyze a model? (Isa)

(1h) Interactive lecture + based on a script for some parts

(Rmarkdown file with the example of Rosenzweig-MacArthur model)

* Analyze the behavior of the model long-term (Box 3 Grainger et al AmNat)
  - Local stability (when possible for long term dynamics) (script)
    + Calculating equilibria
    + What are the Jacobian matrix and eigenvalues (meaning but no math derivation) ?
    + How to interpret the eigenvalues to infer the long term behavior type
* Isoclines / graphical 
 *Phase plane (script)
* Bifurcation diagrams (long term dynamics) (script)
* When results depend on initial conditions => finding all the equilibria of intractable ODE systems (loop to run large series of initial conditions, function searchZeros of package nleqslv)

* Model Usages to answer the question (will try to show some concrete examples of questions to answer with these usages for the model of section 3a)
  - Parameter variation (see bifurcation diagrams + example DeMaz Grazing-Optimization)
  - Comparison with a null model to assess the impact of a process (with or without the process, with different formulation of the process. Example with functional responses (script)
  - Generation of synthetic data on which to run in silico experiments.     - Example of food webs under different regimes of perturbations.

* Parameter exploration and robustness of conclusions
  - Exhaustivity is possible	(tractable)
  - We know the values of parameters from empirical data => allows us to fix or restrain the range of some parameters.
  - Sensitivity analysis: effect size when varying 10% each parameter + look if conclusions are modified if the most sensitive parameters are varied.








