# Temporal data (Day 2)

## Introduction



* in ecology (and evolution) we often (?) have time series data, e.g., population dynamics of elefants, butterflies, protists etc
* an example database for such pop dyn timeseries is the Global Pop Dyn Database

* we have a large body of theory that we can use, instead of naively using a linear regression

* Sibley et al 2025 Science used this e.g. to ask whether there is a general density regulation function (linear/ convex / concave)

## Building a pop dyn model
### Births and deaths immigration and emigration (not treated in this day)

pop dyn models usually have something that goes in and something that goes out, bookkeeping

### including density dependence: the logistic

intriduce rK and r-alpha formulations

### getting an intuition for density dependence: deriving density dependence from consumer-resource model
* "data-driven" vs process-driven (limitation via resources here or space-limited)

### getting an intuition for carrying capacity: the nestbox model

## confronting with data

* different ways: from qualitative to quantitative
* today focus on quantitative/ fitting for paramneter estimation
* for simplicity we use a strategic mdoel for fitting
* maybe resituate in Levins triangle
* today all process-driven

### sibley and likelhood ridges et al
we use use bayesian here and stan (ode solver)

### errors
* obs error
* proc error
* state-space models


## Conclusion
* resituate day in levins triangle
* resituate data vs procxess driven

## References
